package:
  name: ros-humble-wasm-cpp
  version: 1.0
source:
  git_url: https://github.com/ihuicatl/rmw_wasm.git
  git_rev: main
  folder: ros-humble-wasm-cpp/src/work/wasm_cpp

build:
  script:
    sel(unix): build.sh
    sel(emscripten-32): build.sh
  number: 3

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

requirements:
  build:
    - sel(target_platform != 'emscripten-32'): "{{ compiler('cxx') }}"
    - sel(target_platform != 'emscripten-32'): "{{ compiler('c') }}"
    - sel(target_platform == 'emscripten-32'): emscripten_emscripten-32
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - ros-humble-ament-cmake
    - ros-humble-rcutils
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-rcutils
    - ros2-distro-mutex 0.4 humble
  run:
    - sel(target_platform != 'emscripten-32'): cmake
    - python
    - ros-humble-rcutils
    - ros2-distro-mutex 0.4 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
