context:
  version: 1.0

package:
  name: dynmsg
  version: '{{ version }}'

source:
  git_url: https://github.com/osrf/dynamic_message_introspection.git
  git_rev: main
  folder: dynmsg/src/work

build:
  number: 0

requirements:
  build:
    - sel(target_platform != 'emscripten-32'): "{{ compiler('cxx') }}"
    - sel(target_platform != 'emscripten-32'): "{{ compiler('c') }}"
    - sel(target_platform == 'emscripten-32'): emscripten_emscripten-32
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-rcutils
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.4 humble
  run:
    - sel(target_platform != 'emscripten-32'): cmake
    - python
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.4 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}

about:
  license: Apache License 2.0
  license_file: LICENSE
  summary: dynmsg
  dev_url: https://github.com/osrf/dynamic_message_introspection.git
