package:
  name: ros-humble-rmw-wasm-cpp
  version: 1.1.0

source:
  git_url: https://github.com/ihuicatl/rmw_wasm.git
  git_rev: main
  folder: ros-humble-rmw-wasm-cpp/src/work
  patches:
    - fix-fpic.patch

build:
  script:
    sel(unix): build.sh
    sel(emscripten-wasm32): build.sh
  number: 6

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

requirements:
  build:
    - sel(target_platform != 'emscripten-wasm32'): "{{ compiler('cxx') }}"
    - sel(target_platform != 'emscripten-wasm32'): "{{ compiler('c') }}"
    - sel(target_platform == 'emscripten-wasm32'): emscripten_emscripten-wasm32
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-rcutils
    - ros-humble-rcpputils
    - ros-humble-rmw
    - ros-humble-wasm-cpp
    - ros-humble-ament-cmake
    - dynmsg
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.5 humble
  run:
    - sel(target_platform != 'emscripten-wasm32'): cmake
    - python
    - dynmsg
    - ros-humble-rmw
    - ros-humble-wasm-cpp
    - ros-humble-rcutils
    - ros-humble-rcpputils
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
